name: Night Build

on:
  schedule:
    - cron: '0 0 * * *' # will run at 0h00 of every day
  workflow_dispatch: # this will allow us to manually run workflows

jobs:
  check-for-changes:
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.check.outputs.changes }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: 'main'
          fetch-depth: 2 # Fetch the last 2 commits to compare differences

      - name: Check for changes
        id: check
        run: |
          if git diff --name-only HEAD~1..HEAD | grep -q .; then
            echo "::set-output name=changes::true"
          else
            echo "::set-output name=changes::false"
          fi

  build:
    needs: check-for-changes
    if: ${{ needs.check-for-changes.outputs.changes == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: 'main'
          fetch-depth: 0

      - name: Enable verbose output for Maven
        run: mvn clean verify -X -Dmaven.test.failure.ignore=true

      - name: Retry failed Maven dependencies
        run: mvn clean verify -Dmaven.test.failure.ignore=true -U

      - name: Update dependencies to their latest versions
        run: mvn versions:update-properties versions:display-plugin-updates versions:display-dependency-updates -Dmaven.test.failure.ignore=true

      - name: Debug JUnit XML files
        run: ls -la reports/surefire-reports/

      - name: Save JUnit XML test results
        if: always()  # Ensure it runs even if previous steps fail
        run: |
          mkdir -p test-results
          cp reports/surefire-reports/*.xml test-results/

      - name: Upload JUnit XML test results
        uses: actions/upload-artifact@v2
        with:
          name: junit-test-results
          path: test-results/*.xml
