name: Night Build

on:
  schedule:
    - cron: '0 0 * * *' # will run at 0h00 of every day
  workflow_dispatch: # this will allow us to manually run workflows

jobs:
  check-for-changes:
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.check.outputs.changes }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'main'
          fetch-depth: 2 # Fetch the last 2 commits to compare differences

      - name: Check for changes
        id: check
        run: |
          if git diff --name-only HEAD~1..HEAD | grep -q .; then
            echo "::set-output name=changes::true"
          else
            echo "::set-output name=changes::false"
          fi

  build:
    needs: check-for-changes
    if: ${{ needs.check-for-changes.outputs.changes == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'main'
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      #compiles the source code of the project using the settings specified in the pom.xml
      - name: Build with Maven
        run: mvn dependency:copy-dependencies verify -D maven.javadoc.skip=true --file pom.xml
      - name: Build with Maven
        run: mvn dependency:copy-dependencies verify -D maven.javadoc.skip=true --file pom.xml

      - name: Build with Maven 2
        run: mvn clean verify -Dmaven.test.failure.ignore=true
      - name: Build with Maven 2
        run: mvn clean verify -Dmaven.test.failure.ignore=true

      - name: Build and package with Maven
        run: mvn dependency:copy-dependencies -DskipTests package #ignorar os testes neste ponto

      - name: Test
        run: mvn --batch-mode -Dmaven.test.failure.ignore=true test
      - name: Build and package with Maven
        run: mvn dependency:copy-dependencies -DskipTests package #ignorar os testes neste ponto

      - name: Test
        run: mvn --batch-mode -Dmaven.test.failure.ignore=true test

      - name: Coverage per Test Execution
        run: mvn org.jacoco:jacoco-maven-plugin:prepare-agent install -Pcoverage-per-test
      - name: Coverage per Test Execution
        run: mvn org.jacoco:jacoco-maven-plugin:prepare-agent install -Pcoverage-per-test

      - name: Upload target folder
        uses: actions/upload-artifact@v2
        with:
         name: target
         path: |
           ${{ github.workspace }}/target
           ${{ github.workspace }}/reports

      - name: Test Report
        uses: dorny/test-reporter@v1
      - name: Upload target folder
        uses: actions/upload-artifact@v2
        with:
           name: target
           path: |
             ${{ github.workspace }}/target
             ${{ github.workspace }}/reports

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Test Results
          path: ${{ github.workspace }}/target/surefire-reports/TEST-TestSuite.xml
          reporter: java-junit

      - name: Test
        run: mvn -B -Dmaven.test.failure.ignore=true verify

 #Step to cache Maven packages located in the ~/.m2 directory, using a cache key based on the operating system of the runner and the hashes of all pom.xml files in the repository.
#This helps to speed up subsequent workflow runs by avoiding redundant downloads of Maven dependencies.
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
 #         key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Generate reports with maven
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Maven Tests
          path: target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true
      - name: Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Maven Tests
          path: target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true
