name: Night Build

on:
  schedule:
    - cron: '0 0 * * *' # will run at 0h00 of every day
  workflow_dispatch: # this will allow us to manually run workflows

jobs:
  check-for-changes:
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.check.outputs.changes }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: 'main'
          fetch-depth: 2 # Fetch the last 2 commits to compare differences

      - name: Check for changes
        id: check
        run: |
          if git diff --name-only HEAD~1..HEAD | grep -q .; then
            echo "::set-output name=changes::true"
          else
            echo "::set-output name=changes::false"
          fi

  build:
    needs: check-for-changes
    if: ${{ needs.check-for-changes.outputs.changes == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: 'main'
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn dependency:copy-dependencies verify -D maven.javadoc.skip=true --file pom.xml

      - name: Build and package with Maven
        run: mvn dependency:copy-dependencies -DskipTests package

      - name: Test
        run: mvn --batch-mode -Dmaven.test.failure.ignore=true test

      - name: Coverage per Test Execution
        run: mvn org.jacoco:jacoco-maven-plugin:prepare-agent install -Pcoverage-per-test

      - name: Upload target folder
        uses: actions/upload-artifact@v2
        with:
          name: target
          path: |
            ${{ github.workspace }}/target
            ${{ github.workspace }}/reports

      - name: Test Report
        uses: dorny/test-reporter@v1
        with:
          name: Test Results
          path: ${{ github.workspace }}/reports/surefire-reports/TEST-TestSuite.xml
          reporter: java-junit

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          restore-keys: ${{ runner.os }}-maven

      - name: Generate reports with Maven
        uses: dorny/test-reporter@v1
        with:
          name: Maven Tests
          path: reports/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true

