name: Night Build

on:
  schedule:
    - cron: '0 0 * * *' # will run at 0h00 of every day
  workflow_dispatch: # this will allow us to manually run workflows

jobs:
  check-for-changes:
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.changes.outputs.changes }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'main'
          fetch-depth: 2 # Fetch the last 2 commits to compare differences

      - name: Check for changes
        id: changes
        run: |
          if git diff --name-only HEAD~1..HEAD | grep -q .; then
            echo "changes=true" >> $GITHUB_ENV
          else
            echo "changes=false" >> $GITHUB_ENV
          fi

  build:
    if: env.CHANGES == 'true'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'main'
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Print changes variable # para perceber porque é que corre, mas não faz o passo do build quando devia
        run: |
          echo "Changes variable value: ${{ env.CHANGES }}"